name: Android Unit Tests

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'  # Có thể cần nâng cấp version Java
        distribution: 'temurin'
        cache: gradle
        
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew  # Đảm bảo đường dẫn chính xác
      
    - name: Run unit tests
      run: ./gradlew testDebugUnitTest --stacktrace  # Thêm --stacktrace để hiển thị chi tiết lỗi